# This is a basic workflow to help you get started with Actions

name: Docker images build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run the image that already containes Docker
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      
      - name: Docker build React app dev mode
        run: |
          docker build -t ndrean/supermv3-app:dev-mobx-reactrouter -f Dockerfile.dev .
          
      - name: Docker build Nginx webserver
        run: |
          docker build -t ndrean/supermv3-ws:dev-mobx-reactrouter -f ./webserver/Dockerfile.dev ./webserver
          
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Push to Docker Hub
        run: |
          docker push ndrean/supermv3-app:dev-mobx-reactrouter
          docker push ndrean/supermv3-ws:dev-mobx-reactrouter
          
      #- name: Push to Docker Hub
        #uses: docker/build-push-action@v2
        #with:
          #push: true
          #tags:  ndrean/superm-ws:dev-mobx-reactrouter
      
      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
        #run: |
          #echo Add other actions to build,
          #echo test, and deploy your project.
